### ISSUE TITLE
Drawing circuit diagrams

### ISSUE THREAD

**Issue by Krastanov** [rharper2/Juqst.jl#3]
Hello, Robin!

I prepared a small package for drawing diagrams that is just ~300 lines of julia. It offloads the heavy lifting to your local latex install and it uses the `quantikz` latex library. It might help simplify the circuit drawing on your end.

Here is the package: https://github.com/Krastanov/Quantikz (it is already registered and it can be installed from the julia Pkg manager). Here are some examples https://github.com/Krastanov/Quantikz/blob/main/Quantikz.ipynb

Let me know if it would be of use and if I can help with anything.

Best,
Stefan

**Comment by rharper2** [comment]
Hey Stefan,

That looks very interesting indeed. I’ll try and find some time over the holidays for a deeper dive but this definitely looks like it can solve my on-going display problems.

Thanks for letting me know about it. I’ll let you know how I get on.

Robin

**Comment by rharper2** [comment]
It only took me 18 months, but done in the latest version. Thanks.
